name = "ReducedBasisMethods"
uuid = "91da5cd7-58ae-4d67-87db-f03d1c8da121"
authors = ["Michael Kraus"]
version = "0.1.0"

[deps]
GeometricIntegrators = "dcce2d33-59f6-5b8d-9047-0defad88ae06"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
